spring:

  jpa:
    database: postgresql
    show-sql: false
    open-in-view: true
    hibernate:
      ddl-auto: update

  datasource:
    url: ${NWHA_DB_URL}
    username: ${NWHA_DB_USERNAME}
    password: ${NWHA_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

management:
  endpoints:
    web:
      exposure:
        include: "*"